sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.6
  - 3.7-dev
matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
install:
  - pip install tox-travis
  - pip install coveralls
script:
  - tox
after_success: coveralls
